name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - run: go mod download

      - run: go build -v .

      - name: Run linters
        uses: golangci/golangci-lint-action@v3

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - run: go generate ./...

      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  test:
    name: Terraform Provider Acceptance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
          - '1.4.*'
          - '1.5.*'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - run: go mod download
      
      - env:
          TF_ACC: "1"
        run: go test -v -cover ./internal/...
        timeout-minutes: 10

  cover:
    name: Ensure test coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - run: go mod download
      
      - env:
          TF_ACC: "1"
        run: go test -v ./internal/... -coverprofile=coverage.out
        timeout-minutes: 10

      - name: Check Code Coverage
        uses: coverbot-io/coverbot-action@go-coverage
        with:
          format: go
          file: coverage.out
          coverbot_api_key: ${{ secrets.COVERBOT_API_KEY}}
          github_token: ${{ secrets.GITHUB_TOKEN}}
